'use strict';

// 托盘（macOS 菜单栏 / Windows 通知区域）图标尺寸与可读性的回归防线。
//
// 背景 1 —— 尺寸。这里曾经写死 `resize({ width: 32, height: 32 })`。32pt 的框配上
// 当时的资源（墨迹占画布 92%），等效墨迹 29.5pt —— 比菜单栏本身还高（实测刘海机型
// 33pt、非刘海 24pt），于是在菜单栏里顶满上下、还拖出一块底色方块。这类回归没法靠
// 「看一眼代码」发现：`32` 是个完全合理的数字，只有把它和资源文件的实际留白、
// 以及菜单栏的真实高度放在一起算，才能看出它越界。
//
// 背景 2 —— 可读性。现在的资源是彩色企鹅（assets/pingu-tray.png，由
// scripts/build-tray-icon.js 从 assets/pingu-tray.svg 烘出）。企鹅身体是纯黑 #000，
// 而 macOS 菜单栏是半透明的：深色壁纸透出来时黑身体和背景连成一片，只剩红喙黄腹
// 浮着 —— 看着就是「对比度不够」。解法是沿剪影向外扩一圈白色光晕（halo），
// 烘焙脚本里的 dilate()。所以本文件要同时守住三件事：
//
//   · 尺寸合适且墨迹居中（矢量原件上方有 16% 透明边，不裁就会下坠）；
//   · 外缘确实是亮的（光晕还在 —— 谁把 HALO_PT 改成 0，暗底上就退回「糊」）；
//   · 内部确实还是暗的、而且有红有黄（本体没被光晕漂白、也没退化成单色）。
//
// 只查前一条是不够的：前两条的失败模式恰恰是「尺寸完全正确但看着不对」。

const assert = require('assert');
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const root = path.join(__dirname, '..');
const main = fs.readFileSync(path.join(root, 'main.js'), 'utf8');

// 非刘海机型的菜单栏高度，作为「不能顶满」的硬上限参照。刘海机型实测 33pt 更宽松，
// 所以按 24 卡是更严格的那一侧。
const MENU_BAR_PT = 24;
const TRAY_PNG = path.join(root, 'assets', 'pingu-tray.png');
const TRAY_SVG = path.join(root, 'assets', 'pingu-tray.svg');
const BAKE_SCRIPT = path.join(root, 'scripts', 'build-tray-icon.js');

// 矢量原件里的品牌色。企鹅的「彩色」就靠这几个色块，退化成单色就说明图源被换错了。
const BEAK_RGB = [229, 42, 17];   // #E52A11 红喙
const BELLY_RGB = [251, 226, 60]; // #FBE23C 黄腹

function luma(r, g, b) {
  return (0.2126 * r) + (0.7152 * g) + (0.0722 * b);
}

async function trayChecks() {
  const ptMatch = main.match(/const TRAY_ICON_PT = (\d+);/);
  assert(ptMatch, 'main.js must declare TRAY_ICON_PT so the tray size stays greppable');
  const TRAY_ICON_PT = Number(ptMatch[1]);

  const scaleMatch = main.match(/const TRAY_ICON_SCALE = (\d+);/);
  assert(scaleMatch, 'main.js must declare TRAY_ICON_SCALE');
  const TRAY_ICON_SCALE = Number(scaleMatch[1]);

  assert(TRAY_ICON_SCALE >= 2, 'the tray bitmap must be at least 2x, otherwise Retina renders it blurry');
  assert(
    /nativeImage\.createFromBuffer\(sized\.toPNG\(\), \{ scaleFactor: TRAY_ICON_SCALE \}\)/.test(main),
    'the tray icon must hand Tray a bitmap whose scaleFactor makes its logical size TRAY_ICON_PT',
  );
  assert(
    /const px = TRAY_ICON_PT \* TRAY_ICON_SCALE;/.test(main),
    'the tray bitmap must be derived from TRAY_ICON_PT, not a hardcoded pixel size',
  );
  assert(
    !/resize\(\{ width: 32, height: 32 \}\)/.test(main),
    'the oversized 32pt tray icon must not come back',
  );
  // 尺寸已经 1:1 时不能再过一遍 resize —— 眼白在 36px 下只有 1.9px 宽，二次采样会抹掉。
  assert(
    /size\.width === px && size\.height === px/.test(main),
    'the tray icon must skip the resize when the baked bitmap already matches TRAY_ICON_PT',
  );

  // 位图的来源要可复跑：矢量原件 + 烘焙脚本都得在仓库里。
  assert(fs.existsSync(TRAY_SVG), 'the tray vector source must ship so the bitmap can be re-baked');
  assert(fs.existsSync(BAKE_SCRIPT), 'scripts/build-tray-icon.js must ship so the bitmap can be re-baked');
  assert(fs.existsSync(TRAY_PNG), 'the baked Pingu tray bitmap must ship with the app');

  // 光晕必须在烘焙脚本里可调，而不是把白边直接画进位图 —— 否则改厚度就得重画图。
  const bake = fs.readFileSync(BAKE_SCRIPT, 'utf8');
  assert(/const HALO_PT = [\d.]+;/.test(bake), 'scripts/build-tray-icon.js must declare HALO_PT');
  assert(/function dilate\(/.test(bake), 'the halo must be generated by dilating the silhouette');

  // 矢量原件得是彩色的：红喙 + 黄腹 + 黑身 + 白肚都得在。
  const svg = fs.readFileSync(TRAY_SVG, 'utf8');
  for (const hex of ['#E52A11', '#FBE23C', '#000', '#FFF']) {
    assert(svg.includes(hex), `the tray vector source lost its ${hex} fill — is this still the colour Pingu?`);
  }

  const { data, info } = await sharp(TRAY_PNG).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const { width, height, channels } = info;
  const target = TRAY_ICON_PT * TRAY_ICON_SCALE;

  // 位图必须就是目标像素 —— 否则 main.js 会走 resize 分支做二次采样，眼白会糊。
  assert(
    width === target && height === target,
    `assets/pingu-tray.png is ${width}x${height}px but the tray needs ${target}x${target}px `
    + `(TRAY_ICON_PT ${TRAY_ICON_PT} x TRAY_ICON_SCALE ${TRAY_ICON_SCALE}) — re-run: node scripts/build-tray-icon.js`,
  );

  let x0 = width;
  let x1 = -1;
  let y0 = height;
  let y1 = -1;
  for (let y = 0; y < height; y += 1) {
    for (let x = 0; x < width; x += 1) {
      if (data[((y * width + x) * channels) + 3] > 16) {
        if (x < x0) x0 = x;
        if (x > x1) x1 = x;
        if (y < y0) y0 = y;
        if (y > y1) y1 = y;
      }
    }
  }
  assert(y1 >= y0 && x1 >= x0, 'the tray avatar must not be fully transparent');

  const inkW = x1 - x0 + 1;
  const inkH = y1 - y0 + 1;
  const inkPt = TRAY_ICON_PT * (inkH / height);

  // 18pt 的框（含 1.5pt 光晕）⇒ 墨迹约 16pt。留出富余：上限卡到 20pt，
  // 也就是仍然比 24pt 的菜单栏矮一截、上下有可见留白。
  assert(inkPt <= 20, `the tray icon would be ${inkPt.toFixed(1)}pt tall — too tall for a ${MENU_BAR_PT}pt menu bar`);
  assert(inkPt >= 10, `the tray icon would be only ${inkPt.toFixed(1)}pt tall — too small to read`);
  assert(target >= 32, 'the tray bitmap must be at least 32px so Retina has real pixels to use');

  // 墨迹必须居中。矢量原件上方有 16% 透明边，谁把烘焙脚本的裁边/补方去掉，
  // 企鹅就会在菜单栏里往下坠 —— 而「尺寸对不对」是查不出这件事的。
  const offX = Math.abs(((x0 + x1) / 2) - ((width - 1) / 2));
  const offY = Math.abs(((y0 + y1) / 2) - ((height - 1) / 2));
  assert(offX <= 1, `the tray ink is off-centre horizontally by ${offX.toFixed(1)}px — re-run scripts/build-tray-icon.js`);
  assert(offY <= 1, `the tray ink is off-centre vertically by ${offY.toFixed(1)}px — re-run scripts/build-tray-icon.js`);

  // 外缘 / 内部两层采样。外缘 = 距墨迹包围盒边界 ≤2px 的像素，那里应该只有光晕；
  // 内部 = 距边界 ≥5px 的像素，那里应该是企鹅本体。
  let rimCount = 0;
  let rimLuma = 0;
  let rimBright = 0;
  let coreCount = 0;
  let coreDark = 0;
  let bestBeak = Infinity;
  let bestBelly = Infinity;
  let maxSaturation = 0;

  for (let y = y0; y <= y1; y += 1) {
    for (let x = x0; x <= x1; x += 1) {
      const i = (y * width + x) * channels;
      if (data[i + 3] <= 32) continue;
      const edge = Math.min(x - x0, x1 - x, y - y0, y1 - y);
      const r = data[i];
      const g = data[i + 1];
      const b = data[i + 2];
      if (edge <= 2) {
        rimCount += 1;
        rimLuma += luma(r, g, b);
        if (luma(r, g, b) > 160) rimBright += 1;
      }
      if (edge >= 5) {
        coreCount += 1;
        if (luma(r, g, b) < 40) coreDark += 1;
      }
      const dBeak = Math.hypot(r - BEAK_RGB[0], g - BEAK_RGB[1], b - BEAK_RGB[2]);
      const dBelly = Math.hypot(r - BELLY_RGB[0], g - BELLY_RGB[1], b - BELLY_RGB[2]);
      if (dBeak < bestBeak) bestBeak = dBeak;
      if (dBelly < bestBelly) bestBelly = dBelly;
      const max = Math.max(r, g, b);
      if (max > 0) maxSaturation = Math.max(maxSaturation, (max - Math.min(r, g, b)) / max);
    }
  }

  assert(rimCount > 0 && coreCount > 0, 'the tray bitmap is too small to sample a rim and a core');

  // ① 光晕还在：最外一圈应该是亮白（实测平均亮度 230）。HALO_PT 改成 0 的话，
  //    这一圈会变成企鹅的黑身体，平均亮度掉到几十。
  const rimMean = rimLuma / rimCount;
  assert(
    rimMean > 180,
    `the tray icon's outer edge averages ${rimMean.toFixed(0)} luma — the white halo is gone or too thin, `
    + 'so the icon melts into a dark menu bar. Re-run: node scripts/build-tray-icon.js',
  );
  assert(
    (rimBright / rimCount) > 0.7,
    `only ${((rimBright / rimCount) * 100).toFixed(0)}% of the outer edge is bright — the halo is patchy`,
  );

  // ② 本体没被漂白：内部仍要有大片黑（实测 57% 像素亮度 <40）。
  //    「把黑身体换成浅灰」那种深色模式配色会在这里挂掉 —— 它在浅色菜单栏上直接消失。
  const coreDarkShare = coreDark / coreCount;
  assert(
    coreDarkShare > 0.35,
    `only ${(coreDarkShare * 100).toFixed(0)}% of the core is dark — the black Pingu body was brightened, `
    + 'which makes the icon vanish on a light menu bar',
  );

  // ③ 还是彩色的：红喙与黄腹都得真的在（实测色差 0.0 / 6.4）。换成黑白剪影版就会挂。
  assert(bestBeak < 40, `no red beak found (closest #E52A11 is ${bestBeak.toFixed(0)} away) — the tray icon lost its colour`);
  assert(bestBelly < 40, `no yellow belly found (closest #FBE23C is ${bestBelly.toFixed(0)} away) — the tray icon lost its colour`);
  assert(maxSaturation > 0.7, `max colour saturation is only ${maxSaturation.toFixed(2)} — the tray icon is greyscale`);

  const rimNote = `rim ${rimMean.toFixed(0)} luma, core ${(coreDarkShare * 100).toFixed(0)}% dark`;
  console.log(`tray icon checks passed (host ${TRAY_ICON_PT}pt -> ink ${inkW}x${inkH}px = ${(inkW / TRAY_ICON_SCALE).toFixed(1)}x${inkPt.toFixed(1)}pt, bitmap ${target}px, centred, ${rimNote})`);
}

trayChecks().catch((error) => {
  console.error(error);
  process.exit(1);
});
